lua/dropbar/sources/lsp.lua
There seem be cases where a `LspAttach` event does not contain a `data` property with the client identifier inside. In such case the callback function would fail as it simply assumes this data structure to be given.
As it's still unclear why such events happen, it is quite easy to make the callback more robust. Therefore it checks if the data exists and it also verifies if a client could be found. In case that not, it simply does nothing and does not attach to it.
See also [this conversation](https://github.com/Bekaboo/dropbar.nvim/discussions/9#discussioncomment-6046818)
=> Feat: make LspAttached callback more robust

lua/dropbar/menu.lua
*Originally part of #49*
This fixes the updating of preview highlights when:
- closing a submenu and returning to a parent menu
- reopening a submenu that was previously closed
See the GIFs below for a comparison of the behavior before and after.
<details> 
<summary>Before</summary>
> ![bad](https://github.com/Bekaboo/dropbar.nvim/assets/92238946/79f827ba-0147-4037-9fb8-8ee7c8105f99)
</details>
<details> 
<summary>After</summary>
> ![good](https://github.com/Bekaboo/dropbar.nvim/assets/92238946/08301d09-7dd0-4e21-b749-8770ed5d353e)
</details>
This also fixes the updating of current context highlights when returning to a submenu. Prior to these changes, returning to a parent menu would retain the context highlight of the menu entry that was the parent.
Finally, the hover highlighting in …
=> Fix several highlighting issues that occur during menu navigation

lua/dropbar.lua
Prior to these changes, only one window would be updated on `WinResized` events. Also happens to fix something possibly related to #55: `WinResized` events from any window would cause the current window to update the dropbar. For example if an autocompletion plugin is installed like [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), typing during insert mode triggers `WinResized` events on the popup menu which would update the dropbar.
<details>
<summary>Before</summary>
In this gif we can see that only the top left window's dropbar is updated.
</details>
<details>
<summary>After</summary>
</details>
=> fix(dropbar): `WinResized` not updating all affected windows

lua/dropbar.lua, lua/dropbar/bar.lua, lua/dropbar/hlgroups.lua, lua/dropbar/menu.lua, lua/dropbar/sources/path.lua, lua/dropbar/utils/hl.lua
*Originally part of #49*
This PR adds support for a background color on the dropbar. The changes made here are virtually identical to those in #49 (those that pertain to background highlighting), except that the highlight configuration option was removed, and the background color is [instead taken from `hl-WinBar`](https://github.com/Bekaboo/dropbar.nvim/pull/49#discussion_r1255002693). The commits were reorganized for clarity.
Tasks
---
=> Support background highlight

lua/dropbar/hlgroups.lua
Should fix https://github.com/Bekaboo/dropbar.nvim/pull/51#issuecomment-1640664401.
=> Fix `Expected lua table` if `WinBar(NC)` highlight groups are empty

doc/dropbar.txt, lua/dropbar/bar.lua, lua/dropbar/hlgroups.lua, lua/dropbar/sources/init.lua, lua/dropbar/sources/lsp.lua, lua/dropbar/sources/markdown.lua, lua/dropbar/sources/path.lua, lua/dropbar/sources/treesitter.lua
*Originally part of #49*
- Parent directory is now a menu entry for path source
- Current file menu entry has child entries, currently the top level treesitter symbols of the file
<details>
<summary> Demo </summary>
</details>
In #49, I had expressed uncertainty with regards to adding an extra argument to `sources.treesitter.get_symbols()` because its signature would differ from the other `get_symbols()` for the other sources, and was considering instead creating a separate function dedicated to getting the top level TS nodes. However, given this comment (from https://github.com/Bekaboo/dropbar.nvim/pull/49#issuecomment-1624394416):
>   * in addition it would be great to add other sources, for example `lsp` & `markdown` as children to `path` source when appropriate (will look into this …
=> Sources features: add child entries to current file, add parent directory entry

lua/dropbar/menu.lua
Fixes correctness of highlight namespace updating when entering a new `dropbar_menu_t`. 
1. **Before**, this operation was `vim.schedule()`d which would fail if the `dropbar_menu_t` is closed immediately. The scheduling is removed and the namespace is updated immediately instead.
2. A check is done if the previous window is *not* a `dropbar_menu_t` (this is because we want to "force" the previous window to have the highlights of `WinBar` instead of `WinBarNC`, even thought we're technically *not* focused in that window). Then we check that window has, in fact, a DropBar (e.g. user could have some config that disables DropBar on that window, so in that case we don't want to update). **Before**, this check was being done with the wrong window handle, now the correct one is used.
The (1) …
=> Fix: incorrect updating of previous window's highlight namespace

lua/dropbar/hlgroups.lua
Fixes incorrect highlight updates when colorscheme is changed. This is only relevant to this feature branch.
Prior to these changes, any "patched" devicon highlight was not "re-patched" when colorscheme is changed (by patched, I mean "create a separate highlight group for the devicon that inherits the winbar background highlights"). Now this is done.
Additionally, the `ColorScheme` autocmd event now *schedules* the updating of highlights instead of triggering it automatically. This is useful when the user sets some custom highlights after calling `:colorscheme`. Prior to this, if the user did something like:
```lua
vim.cmd('colorscheme <some colorscheme>')
vim.api.nvim_set_hl(0, 'WinBar', { ... })
```
the highlights would be created *before* the `WinBar` highlight is manually set, and …
=> Fix: properly update highlights on colorscheme change

README.md, lua/dropbar/configs.lua, lua/dropbar/hlgroups.lua, lua/dropbar/sources/terminal.lua
Allows using the dropdown menu to quickly switch between terminal buffers. Wrote this for my own config but figured I'd share since it's been useful.
All menu properties can be set to either strings or functions in the config, so it can be integrated easily with any terminal-related plugin. I have mine setup to use toggleterm. It will also work with default nvim terminal buffers.
=> feat: add builtin source for terminal buffers

lua/dropbar/sources/terminal.lua
Realized the terminal source can be much simpler by setting `siblings` and overriding `jump`, instead of overriding `on_click`.
This also makes the current terminal highlight properly in the menu by setting `sibling_idx`.
=> refactor(term): use default menu config, only override jump

doc/dropbar.txt
Fix typo in documentation (bad copy-paste I guess).
Fixes #82
=> docs: remove duplicate tag

lua/dropbar/menu.lua
Allows menus to be created with positions relative to `cursor`, `editor`, etc. 
Main reason for this is that I'm working on a `dropbar_menu_t` implementation of `vim.ui.select`.
=> fix(menu): allow `relative` win settings other than `win`

README.md, doc/dropbar.txt, lua/dropbar/menu.lua
This PR adds the ability to show `virt_text` below each menu entry:
https://github.com/Bekaboo/dropbar.nvim/assets/38540736/b8d0523d-484e-45f7-8572-aab9e48afea1
=> feat(menu): allow showing virtual text below entries

lua/dropbar/menu.lua
problem: since a large portion of `on_update` is inside of a `vim.schedule` closure - if all input buffer text is removed quickly, fzf entries can have their `pos` field removed before the `vim.schedule` callback executes, causing an error. solution: add a check to ensure that `fzf_entry.pos` is not nil before iterating and setting extmarks
fixes #97
=> fix(fzf): ensure `fzf_entry.pos` is non-nil in `on_update`

lua/dropbar/menu.lua
=> fix: revert 2debe82

README.md
Currently this link results in a 404 error.
=> fix(docs): add extension to fzf plugin

README.md, doc/dropbar.txt, lua/dropbar/configs.lua, lua/dropbar/menu.lua
I prefer a floating scrollbar like I had originally implemented - this adds a "floating" option to use no background window, and an option to disable the scrollbar entirely. The current behavior is still the default.
=> feat: optionally position scrollbar over menu

lua/dropbar.lua
Makes dropbar aware of multi-monitor and multiplexer setups by clearing hover highlight when the mouse leaves the nvim window.
=> fix: remove hover highlight on FocusLost

README.md
=> docs: Fix sublist indentation

lua/dropbar/bar.lua
Dropbar doesn't currently escape percent signs in component names which can lead to incorrect names when rendered in the winbar:
For example, after `:e \%asdf` (top is dropbar, bottom is default statusline).
Escaping the percent signs before highlighting components seems to fix this:
=> fix(bar): Escape percent signs in symbol_t component names

.luarc.json
Makes sure we get proper type checking for Neovim's API and the whole project.
=> fix(types): add ./lua and $VIMRUNTIME/lua in workspace.library

lua/dropbar/configs.lua, lua/dropbar/menu.lua, lua/dropbar/utils/menu.lua
This PR fixes the issue with fzf placement I mentioned in #123.
=> feat(fzf): allow fzf win_configs to contain functions, fix vertical offsets

lua/dropbar.lua
Seems quite impossible, but the window may not exist when `WinSized` is triggered. I don't know the reason but I think avoiding this situation is acceptable.
In my case, this may be because of the plugin:
https://github.com/mikesmithgh/kitty-scrollback.nvim/blob/fd75b297d82e6fb5fe724373cd95d2422b31d7b9/lua/kitty-scrollback/autocommands.lua#L55-L82
=> fix(event): avoid iterating when table is not exist

README.md, lua/dropbar/utils/menu.lua
Adds optional preview support to the ui-select menu, via the `preview` and `preview_close` fields on the options table.
=> feat(ui-select): support optional preview of items

plugin/dropbar.lua
If the user writes a new file by `nvim <new_file_name>`, the `BufReadPost` will not be triggered, instead, `BufNewFile` will be triggered.
=> fix(autocmd): add missing setup event `BufNewFile`

README.md, doc/dropbar.txt, lua/dropbar/configs.lua, lua/dropbar/menu.lua, lua/dropbar/sources/path.lua
Adds support for previewing files from the path source.
=> feat: support preview for entries in path source menus

lua/dropbar/configs.lua
Neovim v0.110-dev shows a warning of a deprecated method `vim.tbl_islist`.
Use `vim.islist` if available
=> fix: use vim.islist if available

lua/dropbar/sources/path.lua
Closes #174
After testing, both `vim.api.nvim_buf_get_name()` and `vim.fn.getcwd()` can return drive letters as `c:` or `C:`. So to standardize this, we will convert the drive letter to uppercase.
If has any suggestions, please let me know.
=> fix: get_symbols error caused by drive letter on Windows

.gitignore
`:helptags ALL` creates this file and `git status` then keeps telling me about it. Other nvim plugins have this in their .gitignores, so add it here as well to silence it.
=> chore: add doc/tags to .gitignore

plugin/dropbar.lua
`setup` is execute twice when using `lazy.nvim` load this plugin with `opts = {...}`.
~This is also a workaround for https://github.com/Bekaboo/dropbar.nvim/issues/141.~
=> fix(setup): avoid setup twice when using lazy.nvim

lua/dropbar/sources/path.lua
If the devicon does not exist for a filename/extension, we try to find it by the filetype buffer option value first before defaulting to the default icon for a file. This is similar to the behavior for lualine plugin.
This is useful for when the filetype is the buffer not by extension but by other means, e.g. from shebang values or custom filetype plugins.
=> fix: add filetype devicon as fallback

.github/workflows/release-please.yml
Bug:    Not triggering push-to-luarocks after release-please.
Fix:    Use personal access token (PAT), see discussion:
https://github.com/nvim-neorocks/sample-luarocks-plugin/issues/1
=> ci: release-please workflow now requires PAT to trigger push-to-luarocks

lua/dropbar/hlgroups.lua
https://github.com/Bekaboo/dropbar.nvim/issues/118 has been fixed on master, and so there's no need for this workaround when using nightly.
=> fix(hl): don't remove winbar background in nightly

README.md, doc/dropbar.txt
Removing some invalid references to the `general` section that was deprecated in https://github.com/Bekaboo/dropbar.nvim/commit/54590c06469eb5fbbcc6a417c91cbc250a801664.
=> docs: remove stale references to general section

README.md
These are necessary to correctly install the dependency.
=> docs(readme): add build commands to telescope-fzf-native

README.md, doc/dropbar.txt, lua/dropbar/bar.lua, lua/dropbar/configs.lua, lua/dropbar/sources/lsp.lua, lua/dropbar/sources/markdown.lua, lua/dropbar/sources/path.lua, lua/dropbar/sources/treesitter.lua, lua/dropbar/utils/bar.lua
Add config `min_widths` to config minimum width of dropbar symbols when truncated.
For example, setting `sources.path.min_widths = {20, 10}` forces the last symbol of path (which is filename) has width at least 20 when it is truncated, and the last but one (which is parent directory name) has width at least 10.
Add this config for souces path, lsp, treesitter and markdown.
=> feat(bar): add config `min_widths`

README.md, doc/dropbar.txt, lua/dropbar/bar.lua, lua/dropbar/hlgroups.lua
I'm working on a colorscheme and needed to separate these two highlights to get the bar looking the way I wanted. Before this change, setting a `fg` color on the `DropBarCurrentContext` highlight group would override the icon's highlight
=> separate highlights for current context icon and name
